import Head   from "next/head"

import { useEffect, useState } from "react"
import { MyTable } from "./components/Table"

import { getWalletInverseBTC } from "./modules/APImodules"

export default function Home() {
  const [balance, setBalance] = useState()

  useEffect( () => {
    getWalletInverseBTC()
      .then(res => { 
        res.ret_msg == "OK" ? setBalance( res ) : "undefined"
      })
  }, [])

  return (
    <>
      <Head>
        <title>GVT Bybit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <p>Response: { balance ? "OK" : "Pending..." }</p>
          <p>Inverse Perpetual Wallet Balance: 
            { balance ? " " + balance.result.BTC.equity + " BTC" : " undefined" }
          </p>
        </div> <br />
        <MyTable />
      </main>
    </>
  )
}
